close all;
clear;
clc;
addpath cores objects functions callbacks dummies;

%% Initialization
%%GUI
global UP;
global CLSE;
global STOP;
global TRNSTN;
global HNTS;
global CNST;
global pllt;
global fgr;
global log;
global axs;
global txt;
global obj;
global me_count;
global crcl;
global arrw;

UP = true;
CLSE = false;
STOP = false;
TRNSTN = false;
HNTS = {{'The above system contains a wireless network under DoS attack. A receiver and its';
    'beamformig plane is shown on the left. Please left-click on the board and hold to';
    'create a transmitter.'};
    {'The transmission power of the transmitter is shown as a circular progress bar around it.';
    'You can control the power by either right-clicking on the transmitter or left-clicking on';
    'its progress bar. Also, you can left-click on the board and hold to add an interferer.'};
    {'The transmission power of the interferer is controlled similarly to the transmitter. Also,';
    'you can right-click on the board and hold to add a scatterer. Please note that later, ';
    'during the simulation, you can add multiple interefers or scatters to the system.'};
    {'Directions of objects are set by rotating the arrow around them. Furthermore, if you';
    'want to remove an object, you can middle-click on it. Now, please add another';
    'interferer or scatterer to continue.'}};
CNST = struct('FigureTitle', 'Interferers DoS Attack Simulation',...
    'FigureWidth',600,...
    'FigureHeight',670,...
    'FontName','Trebuchet MS',... %Everything
    'CircleResolution',60,... %Receiver | ME
    'FramePerSecond',30,... %Transition
    'TransitionSlow',0.4,... %Transition
    'TransitionNormal',0.2,... %Transition
    'TransitionFast',0.05,... %Transition
    'FontSizeTiny',8,... %Input
    'FontSizeSmall',10,... %Input
    'FontSizeMedium',12,... %Button | Message
    'FontSizeLarge',32,... %Message
    'FontWeightNormal','normal',... %Input | Message
    'FontWeightBold','bold',... %Button | Message
    'DistanceSmall',5,... %Group(Cover) | Message | Input | Board
    'DistanceMedium',10,... %Between Objects
    'DistanceLarge',25,... %Between MEs and Board Edges
    'CurvatureSmall',2,... %Input
    'CurvatureMedium',5,... %Button | Message
    'LineWidthTiny',1,... %Input | Receiver
    'LineWidthSmall',2,... %ME
    'LineWidthMedium',2.5,... %Input
    'ObjectWidthSmall',100,... %Button
    'ObjectWidthMedium',150,... %Button
    'ObjectWidthLarge',200,... %Button | Input
    'ObjectHeightTiny',20,... %Tick
    'ObjectHeightSmall',30,... %Input
    'ObjectHeightMedium',40,... %Transition | Button
    'ObjectHeightLarge',50,... %Message
    'ReceiverMarginRadius',155,... %Receiver
    'ReceiverOuterRadius',150,... %Receiver
    'ReceiverInnerRadius',30,... %Receiver
    'MeMarginRadius',28,... %ME
    'MeOuterRadius',23,... %ME
    'MeInnerRadius',15,... %ME
    'MeArrowHeight',5,... %ME
    'MeHookRadius',5,... %ME
    'MeScattererStationary',0.9,... %ME
    'MeScattererMinAttenuation',0.6); %ME
pllt = struct('Background',[189 195 199]/255,...
    'TickDescription',[44 62 80]/255,...
    'TickBackground',[236 240 241]/255,...
    'TickBackground_focused',[250 211 144]/255,...
    'TickEdge',[44 62 80]/255,...
    'TickFront',[44 62 80]/255,...
    'ButtonBackground',[0 184 148]/255,...
    'ButtonBackground_focused',[85 239 196]/255,...
    'ButtonText',[236 240 241]/255,...
    'MessageBack',[253 203 110]/255,...
    'MessageIconBack',[225 112 85]/255,...
    'MessageIconText',[44 62 80]/255,...
    'MessageText',[44 62 80]/255,...
    'InputDescription',[44 62 80]/255,...
    'InputBackground',[236 240 241]/255,...
    'InputEdge',[44 62 80]/255,...
    'InputText',[52 73 94]/255,...
    'InputLine',[52 152 219]/255,...
    'BoardBackground',[236 240 241]/255,...
    'ReceiverMargin',[44 62 80]/255,...
    'ReceiverBack',[236 240 241]/255,...
    'ReceiverFront',[60 99 130]/255,...
    'ReceiverEstimationCurve',[155 89 182]/255,...
    'ReceiverBeamformingCurve',[52 152 219]/255,...
    'MeMargin',[44 62 80]/255,...
    'MeMargin_focused',[183 21 64]/255,...
    'MeBack',[236 240 241]/255,...
    'MeSlider',[130 204 221]/255,...
    'MeFront_transmitter',[52 152 219]/255,...
    'MeFront_scatterer',[155 89 182]/255,...
    'MeFront_interferer',[230 126 34]/255,...
    'MeFront_focused',[183 21 64]/255,...
    'MeStartHookLine',[44 62 80]/255,...
    'MeStartHookFace',[44 62 80]/255,...
    'MeEndHookLine',[44 62 80]/255,...
    'MeEndHookFace',[26 188 156]/255,...
    'MeText',[236 240 241]/255);
obj = struct('Parent',{},'Name',{},'Type',{},'Pointer',{},'Visible',{},'Active',{},'Handle',{},'Feature',{});
me_count = 0;
crcl = [0 cos((0:1/CNST.CircleResolution:1)*2*pi);0 sin((0:1/CNST.CircleResolution:1)*2*pi)];
arrw = [1 0 0;0 0.5 -0.5];
log = figure('Visible', 'off');
axs = [];
txt = [];

%% Graphical Realization
fgr = figure('Units','pixels','Position',[0 0 CNST.FigureWidth CNST.FigureHeight],...
    'Name',CNST.FigureTitle,'NumberTitle','off','Resize','off',...
    'MenuBar','none',...
    'Color',pllt.Background,...
    'WindowButtonDownFcn',@cllbckClickDownWindow,'WindowButtonMotionFcn',@cllbckHoverCheck,...
    'UserData',struct('CurrentIndex','','PointerOffset','','OldPowerRatios',''));
movegui(fgr,'center');
delete(log);

funcMakeObject(nan,'cntrl','grp','','',...
    true,true,...
    [0 0],...
    [CNST.FigureWidth CNST.FigureHeight]);
funcMakeObject(nan,'chck','tick','Show the Hints','',...
    true,true,...
    [CNST.FigureWidth/2 (CNST.FigureHeight+CNST.ObjectHeightMedium+CNST.DistanceMedium)/2],...
    [nan nan]);
funcMakeObject(nan,'strt','btn','','Start',...
    true,true,...
    [CNST.FigureWidth/2 (CNST.FigureHeight-CNST.DistanceMedium-CNST.ObjectHeightSmall)/2],...
    [CNST.ObjectWidthSmall CNST.ObjectHeightMedium]);