function obj_crte()
global HNTS;
global CNST;
global obj;

funcFloatParent(dmmyGetIndex({'cntrl' 'intrctn'}),[false false],...
    {[0 -CNST.ObjectHeightMedium] [0 CNST.ObjectHeightMedium]});

funcRecoordinateGroup(dmmyGetIndex('cntrl'),...
    [nan 0],...
    [nan CNST.FigureHeight-CNST.FigureWidth]);
funcRecoordinateGroup(dmmyGetIndex('intrctn'),...
    [nan CNST.FigureHeight-CNST.FigureWidth],...
    [nan CNST.FigureWidth]);

obj(dmmyGetIndex('cvrge')).Handle.Text.String = num2str(eval(obj(dmmyGetIndex('cvrge')).Handle.Text.String)/10);
obj(dmmyGetIndex('smbl_tme')).Handle.Text.String = num2str(eval(obj(dmmyGetIndex('smbl_tme')).Handle.Text.String)*2);
obj(dmmyGetIndex('avg_vlcty')).Handle.Text.String = num2str(eval(obj(dmmyGetIndex('avg_vlcty')).Handle.Text.String)/40);

funcCoverChild(dmmyGetIndex({'crte' obj(strcmp({obj.Type},'inpt')).Name}),false(1,sum(strcmp({obj.Type},'inpt'))+1));

if ~obj(dmmyGetIndex('chck')).Feature.Status
    funcMakeObject(nan,'hnt','msg','i','Add a transmitter in order to continue.',...
        true,true,...
        [nan nan],...
        [nan nan]);
else
    funcMakeObject(nan,'hnt','msg','i',HNTS{1},...
        true,true,...
        [nan nan],...
        [nan nan]);
end
funcMakeObject(nan,'wrld','brd','','',...
        true,true,...
        [nan nan],...
        [nan nan]);
funcMakeObject([nan nan],'rcvr','rcvr','','',...
        true,true,...
        [nan nan],...
        [nan nan]);

funcFadeParent(dmmyGetIndex({'cntrl' 'intrctn'}),[true true]);
end