function obj_strt()
global CNST;

funcFadeParent(dmmyGetIndex('cntrl'),false);
funcCoverChild(dmmyGetIndex({'strt' 'chck'}),[false false]);

funcMakeObject(nan,'crte','btn','','Initiate the System',...
    true,true,...
    [CNST.FigureWidth/2 CNST.ObjectHeightMedium/2],...
    [CNST.ObjectWidthLarge CNST.ObjectHeightMedium]);

funcMakeObject(nan,'intrctn','grp','','',...
    false,false,...
    [0 0],...
    [CNST.FigureWidth CNST.FigureHeight]);

cntr = 1;
funcMakeObject(nan,'fltr','inpt','DoA Estimation Limit Margin','[0.1 0.5]',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'mthd','inpt','DoA Estimation Method','MVD',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'vrnce','inpt','Noise Variance','0.01',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'gmma','inpt','Fading \gamma Parameter','1.4',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'sgma','inpt','Shdowing \sigma Parameter','0.0392',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'mu','inpt','Shdowing \mu Parameter','-0.7128',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'arr_size','inpt','Antenna Array Size','12',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'mdltn_lvl','inpt','Modulation Level','4',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'athntctn','inpt','Authentication Code','Authentication',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'rptn','inpt','Symbol Repetitions','1',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'smbl_tme','inpt','Symbol Time (s)','0.00577',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'avg_vlcty','inpt','Average Velocity (kph)','72',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);
cntr = cntr + 1;
funcMakeObject(nan,'cvrge','inpt','Coverage Radius (m)','50',...
    true,true,...
    [CNST.FigureWidth/2 (cntr-1)*(CNST.ObjectHeightSmall+CNST.DistanceMedium)+CNST.ObjectHeightSmall/2],...
    [CNST.ObjectWidthMedium CNST.ObjectHeightSmall]);

temp = 0.5*(CNST.FigureHeight-cntr*(CNST.ObjectHeightSmall+CNST.DistanceMedium)-CNST.ObjectHeightMedium);
funcRecoordinateGroup(dmmyGetIndex('cntrl'),...
    [nan temp],...
    [nan CNST.ObjectHeightMedium]);
temp = temp + CNST.ObjectHeightMedium + CNST.DistanceMedium;
funcRecoordinateGroup(dmmyGetIndex('intrctn'),...
    [nan temp],...
    [nan cntr*(CNST.ObjectHeightSmall+CNST.DistanceMedium)-CNST.DistanceMedium]);

funcFloatParent(dmmyGetIndex({'cntrl' 'intrctn'}),[true true],...
    {[0 CNST.ObjectHeightMedium] [0 -CNST.ObjectHeightMedium]});
end

